"""Monetization Paths API routes."""

from fastapi import APIRouter, Depends

from app.core.dependencies import get_current_user_id
from app.schemas.monetization import MonetizationPath, MonetizationPathsResponse

router = APIRouter(prefix="/monetization", tags=["monetization"])


@router.get("/paths", response_model=MonetizationPathsResponse)
async def get_monetization_paths(user_id: str = Depends(get_current_user_id)):
    """Get AI-recommended monetization paths based on the user's skill profile."""
    # In production, these would be generated by the AI based on stored skill profiles
    paths = [
        MonetizationPath(
            id="freelance-consulting",
            title="UI/UX Consulting",
            category="Services",
            description="Offer high-value UI/UX consulting to startups and agencies.",
            match_score=95,
            estimated_revenue_min=3000,
            estimated_revenue_max=8000,
            time_to_revenue="1-2 weeks",
            difficulty="intermediate",
            required_skills=["UI/UX Design", "Project Management"],
            implementation_steps=[
                "Create a consulting portfolio page",
                "Set up a booking system",
                "Define service packages ($150-250/hr)",
                "Publish case studies",
                "Launch outreach campaign",
            ],
            recommended_tools=["Calendly", "Stripe", "Notion"],
        ),
        MonetizationPath(
            id="online-course",
            title="React & TypeScript Course",
            category="Digital Products",
            description="Create a comprehensive course leveraging your dev and teaching skills.",
            match_score=91,
            estimated_revenue_min=2000,
            estimated_revenue_max=10000,
            time_to_revenue="4-8 weeks",
            difficulty="intermediate",
            required_skills=["React Development", "Content Writing"],
            implementation_steps=[
                "Outline 8-12 module curriculum",
                "Record video lessons",
                "Build practice projects",
                "Set up course platform",
                "Launch with early-bird pricing",
            ],
            recommended_tools=["Gumroad", "Loom", "Notion"],
        ),
        MonetizationPath(
            id="template-shop",
            title="Design Template Store",
            category="Digital Products",
            description="Sell UI/UX templates and design kits for passive income.",
            match_score=88,
            estimated_revenue_min=500,
            estimated_revenue_max=3000,
            time_to_revenue="2-4 weeks",
            difficulty="beginner",
            required_skills=["UI/UX Design"],
            implementation_steps=[
                "Create 5-10 high-quality templates",
                "Set up Gumroad store",
                "Write product descriptions",
                "Share on social media",
                "Build email list for releases",
            ],
            recommended_tools=["Figma", "Gumroad", "ConvertKit"],
        ),
    ]

    return MonetizationPathsResponse(
        paths=paths,
        summary=(
            "Based on your skill profile, we identified 3 high-potential monetization paths. "
            "UI/UX Consulting offers the quickest path to revenue, while the React course "
            "has the highest revenue ceiling."
        ),
    )


@router.post("/paths/{path_id}/plan")
async def generate_monetization_plan(
    path_id: str,
    user_id: str = Depends(get_current_user_id),
):
    """Generate a detailed implementation plan for a specific monetization path."""
    return {
        "path_id": path_id,
        "plan": {
            "title": f"Implementation plan for {path_id}",
            "estimated_setup_time": "2-4 weeks",
            "weekly_milestones": [
                {"week": 1, "tasks": ["Research competitors", "Define value proposition"]},
                {"week": 2, "tasks": ["Create initial assets", "Set up platform"]},
                {"week": 3, "tasks": ["Beta launch", "Collect feedback"]},
                {"week": 4, "tasks": ["Full launch", "Begin marketing"]},
            ],
        },
    }
